### ISSUE TITLE
install.sh missing?

### ISSUE THREAD

**Issue by dannyboy1121** [sri-arjuna/tui#2]
Following git and / or wget instructions for other Linux, sudo sh install.sh fails. Script appears to be missing?

**Comment by sri-arjuna** [comment]
I've changed the installation method using the automake tools.

You can install now, using: (leave --prefix unset to install to /usr/local, or change to /usr if you prefer)

```
./configure --prefix=/
make && sudo make install
```

This change has happend so it better alignes with other GNU/Linux package installations.

**Comment by sri-arjuna** [comment]
Please update the code first, i've just submited some changes.

eae93415c56273d4854c2f2297911fc0b921d3d5
